version: '3.7'

services:
  mt:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    image: twb_mt
    command: /start.sh
    restart: unless-stopped
    # runtime: nvidia  # Comment out in local
    ports:
      - 8001:8000
    volumes:
      - ./app:/app
      - ./.vols/translation-models:/app/models
    env_file:
      - .env/.dev

