version: '3.7'

services:
  mt:
    build:
      context: .
      dockerfile: ./compose/dev/app/Dockerfile
      # dockerfile: ./compose/dev/app/Dockerfile-gpu
    image: twb_mt_dev
    command: /start.sh
    restart: unless-stopped
    # runtime: nvidia  # Comment out in local
    ports:
      - 8001:8000
    volumes:
      - .:/app
      - /translation-models:/models
    env_file:
      - .env/.dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/dev/app/Dockerfile
      # dockerfile: ./compose/dev/app/Dockerfile-gpu
    image: celery_worker_dev
    command: /start-celeryworker
    volumes:
      - .:/app
      - /translation-models:/models
    env_file:
      - .env/.dev
    depends_on:
      - redis
